version: "3.9"

services:
  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: '6zk5RX34i4OsBsjA7xBEmQfi8PmEa2ziJ5n'
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: '07Tu4Lc7Srft06QPRvJhLqhJm0gdLpwr3Nh'
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: '6zk5RX34i4OsBsjA7xBEmQfi8PmEa2ziJ5n'
      KC_HOSTNAME: 'localhost'
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    depends_on:
      - keycloak-db
    command: start-dev
    networks:
      - keycloak-network
    restart: unless-stopped

volumes:
  keycloak-db-data:
  keycloak-data:

networks:
  keycloak-network:
